-- Create demo obituaries for existing users
INSERT INTO dde_obituaries (
  user_id, deceased_first_name, deceased_last_name, birth_date, death_date, 
  gender, birth_place, death_place, relationship_status, cause_of_death,
  main_text, trauerspruch, introduction, location_date, last_residence,
  family_members, life_events, background_image, font_family, color_theme,
  orientation, frame_style, photo_url,
  is_published, published_at, publishing_fee, payment_status, published_duration_days, views_count
) VALUES
-- User 1: Multiple obituaries
('e4d4d221-d897-41fb-9f90-55cca7579e14', 'Elisabeth', 'Müller', '1955-03-15', '2024-11-20', 
 'weiblich', 'Hamburg', 'Hamburg', 'verheiratet', 'natuerlich',
 'In liebevoller Erinnerung an eine wunderbare Ehefrau, Mutter und Großmutter, die uns mit ihrer Güte und Weisheit bereichert hat.',
 'Die Erinnerung ist ein Fenster, durch das wir dich sehen können, wann immer wir wollen.',
 'Nach kurzer schwerer Krankheit ist unsere geliebte Elisabeth friedlich eingeschlafen.',
 'Hamburg, den 22. November 2024', 'Alsterchaussee 42, Hamburg',
 '[{"firstName": "Hans", "lastName": "Müller", "relationship": "ehemann"}, {"firstName": "Sarah", "lastName": "Müller", "relationship": "tochter"}, {"firstName": "Max", "lastName": "Müller", "relationship": "enkel"}]',
 '{}', 'memorial-bg-1.jpg', 'memorial', 'light', 'portrait', 'elegant',
 'https://picsum.photos/400/500?random=11',
 true, NOW() - INTERVAL '5 days', 149.00, 'completed', 30, 156),

('e4d4d221-d897-41fb-9f90-55cca7579e14', 'Wilhelm', 'Müller', '1925-08-10', '2024-10-15', 
 'männlich', 'Bremen', 'Hamburg', 'verwitwet', 'natuerlich',
 'Ein Leben voller Güte und Weisheit ist zu Ende gegangen. Unser geliebter Vater und Großvater hat uns gelehrt, was Liebe und Zusammenhalt bedeuten.',
 'Was man tief in seinem Herzen besitzt, kann man nicht durch den Tod verlieren.',
 'Unser geliebter Vater und Großvater ist nach einem erfüllten Leben friedlich entschlafen.',
 'Hamburg, den 17. Oktober 2024', 'Seniorenheim Alstertal',
 '[{"firstName": "Hans", "lastName": "Müller", "relationship": "sohn"}, {"firstName": "Sarah", "lastName": "Müller", "relationship": "enkelin"}]',
 '{}', 'memorial-bg-2.jpg', 'elegant', 'warm', 'portrait', 'double',
 'https://picsum.photos/400/500?random=12',
 true, NOW() - INTERVAL '10 days', 199.00, 'completed', 60, 234),

-- User 2: Single obituary
('d0e255bc-b68e-42f1-bfeb-9e4921b0bb8f', 'Robert', 'Schmidt', '1960-12-03', '2024-11-18', 
 'männlich', 'Berlin', 'Berlin', 'verheiratet', 'unnatuerlich',
 'Viel zu früh musstest du von uns gehen. Du bleibst unvergessen in unseren Herzen und lebst in unseren Erinnerungen weiter.',
 'Die Liebe hört niemals auf.',
 'Fassungslos und voller Trauer nehmen wir Abschied von unserem geliebten Robert.',
 'Berlin, den 20. November 2024', 'Prenzlauer Berg',
 '[{"firstName": "Anna", "lastName": "Schmidt", "relationship": "ehefrau"}, {"firstName": "Tim", "lastName": "Schmidt", "relationship": "sohn"}, {"firstName": "Lisa", "lastName": "Schmidt", "relationship": "tochter"}]',
 '{}', 'memorial-bg-3.jpg', 'serif', 'dark', 'portrait', 'simple',
 'https://picsum.photos/400/500?random=13',
 true, NOW() - INTERVAL '3 days', 299.00, 'completed', 90, 189),

-- User 3: Multiple obituaries
('5070f12b-74cf-42c8-a33d-d8751f8f1ed2', 'Margarete', 'Weber', '1948-07-22', '2024-11-10', 
 'weiblich', 'München', 'München', 'verheiratet', 'natuerlich',
 'Eine liebevolle Mutter und Großmutter, die uns allen so viel Liebe und Geborgenheit geschenkt hat.',
 'Geliebt wirst du immer sein, vergessen niemals.',
 'Unsere geliebte Mutter ist nach kurzer Krankheit friedlich eingeschlafen.',
 'München, den 12. November 2024', 'Maximilianstraße 15, München',
 '[{"firstName": "Karl", "lastName": "Weber", "relationship": "ehemann"}, {"firstName": "Peter", "lastName": "Weber", "relationship": "sohn"}, {"firstName": "Maria", "lastName": "Weber", "relationship": "schwiegertochter"}]',
 '{}', 'memorial-bg-1.jpg', 'memorial', 'light', 'portrait', 'elegant',
 'https://picsum.photos/400/500?random=14',
 true, NOW() - INTERVAL '11 days', 199.00, 'completed', 60, 178),

('5070f12b-74cf-42c8-a33d-d8751f8f1ed2', 'Heinrich', 'Weber', '1920-03-05', '2024-09-22', 
 'männlich', 'München', 'München', 'verheiratet', 'natuerlich',
 'Unser geliebter Großvater ist nach einem langen, erfüllten Leben friedlich eingeschlafen. Seine Weisheit und Güte werden uns immer begleiten.',
 'Ein erfülltes Leben hat seine Zeit, die Erinnerung daran ist ewig.',
 'Nach 104 Jahren eines erfüllten Lebens ist unser geliebter Patriarch friedlich entschlafen.',
 'München, den 24. September 2024', 'Seniorenresidenz Schwabing',
 '[{"firstName": "Karl", "lastName": "Weber", "relationship": "sohn"}, {"firstName": "Margarete", "lastName": "Weber", "relationship": "schwiegertochter"}, {"firstName": "Peter", "lastName": "Weber", "relationship": "enkel"}]',
 '{}', 'memorial-bg-2.jpg', 'elegant', 'warm', 'portrait', 'double',
 'https://picsum.photos/400/500?random=15',
 true, NOW() - INTERVAL '60 days', 149.00, 'completed', 90, 312),

-- User 4: Single obituary
('6263dcf0-0005-43db-b0b6-981d6ee66e8e', 'Johann', 'Wagner', '1952-01-08', '2024-10-25', 
 'männlich', 'Köln', 'Köln', 'verheiratet', 'natuerlich',
 'Ein liebevoller Vater und Großvater, der immer für seine Familie da war und uns mit seiner ruhigen Art Halt gegeben hat.',
 'Die schönsten Menschen bleiben unvergessen.',
 'Unser geliebter Familienvater ist nach kurzer schwerer Krankheit verstorben.',
 'Köln, den 27. Oktober 2024', 'Bergisch Gladbach',
 '[{"firstName": "Maria", "lastName": "Wagner", "relationship": "ehefrau"}, {"firstName": "Michael", "lastName": "Wagner", "relationship": "sohn"}, {"firstName": "Sandra", "lastName": "Wagner", "relationship": "tochter"}]',
 '{}', 'memorial-bg-3.jpg', 'serif', 'light', 'portrait', 'simple',
 'https://picsum.photos/400/500?random=16',
 true, NOW() - INTERVAL '27 days', 249.00, 'completed', 60, 203),

-- User 5: Multiple obituaries
('23a88656-8d11-41d0-9073-d9cfb7aa34ff', 'Helga', 'Becker', '1958-11-14', '2024-11-22', 
 'weiblich', 'Frankfurt', 'Frankfurt', 'verheiratet', 'natuerlich',
 'In stiller Trauer nehmen wir Abschied von unserer geliebten Helga, die uns mit ihrer Herzlichkeit und ihrem Lachen bereichert hat.',
 'Du warst das Licht in unserem Leben.',
 'Nach tapferem Kampf gegen eine schwere Krankheit ist unsere geliebte Helga friedlich eingeschlafen.',
 'Frankfurt am Main, den 24. November 2024', 'Westend, Frankfurt',
 '[{"firstName": "Thomas", "lastName": "Becker", "relationship": "ehemann"}, {"firstName": "Julia", "lastName": "Becker", "relationship": "tochter"}, {"firstName": "David", "lastName": "Becker", "relationship": "sohn"}]',
 '{}', 'memorial-bg-1.jpg', 'memorial', 'light', 'portrait', 'elegant',
 'https://picsum.photos/400/500?random=17',
 true, NOW() - INTERVAL '1 day', 149.00, 'completed', 30, 67),

('23a88656-8d11-41d0-9073-d9cfb7aa34ff', 'Klaus', 'Becker', '1930-05-20', '2024-08-15', 
 'männlich', 'Frankfurt', 'Bad Homburg', 'verwitwet', 'natuerlich',
 'Unser geliebter Großvater hat ein langes, erfülltes Leben gelebt und ist nun zu seiner geliebten Frau zurückgekehrt.',
 'Die Liebe überdauert den Tod.',
 'Friedlich und umgeben von seiner Familie ist unser geliebter Patriarch eingeschlafen.',
 'Bad Homburg, den 17. August 2024', 'Pflegeheim Sonnenberg',
 '[{"firstName": "Thomas", "lastName": "Becker", "relationship": "sohn"}, {"firstName": "Julia", "lastName": "Becker", "relationship": "enkelin"}, {"firstName": "David", "lastName": "Becker", "relationship": "enkel"}]',
 '{}', 'memorial-bg-2.jpg', 'elegant', 'warm', 'portrait', 'double',
 'https://picsum.photos/400/500?random=18',
 true, NOW() - INTERVAL '99 days', 199.00, 'completed', 90, 445);