// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zayhzpwudggrvuoeicoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpheWh6cHd1ZGdncnZ1b2VpY29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDU1MzIsImV4cCI6MjA3MTI4MTUzMn0.9EAWSvtL2VrVh78rltHb9384DAF3CyX9jUkCRgVjOcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});